name: Build and Push Docker Image

on:
  push:
    branches:
      - develop

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker buildx create --use
          IMAGE_TAG="latest"
          REPO_NAME="ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}"
          docker buildx build --platform linux/amd64,linux/arm64 -t $REPO_NAME:$IMAGE_TAG .

      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker Image to GitHub Container Registry
        run: |
          IMAGE_TAG="latest"
          REPO_NAME="ghcr.io/${{ github.repository_owner }}/${{ github.repository_name }}"
          docker push $REPO_NAME:$IMAGE_TAG
