name: Store Artifact to GitHub Packages

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Your Project
        run: |
          cd $GITHUB_WORKSPACE
          ./gradlew clean build

      - name: Publish Artifact to GitHub Packages
        run: |
          echo ${{ secrets.TOKEN_REGISTRY }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          docker build -t docker.pkg.github.com/importantotter/practise-test/image:tag .
          docker push docker.pkg.github.com/importantotter/practise-test/image:tag
